--- 
abstract: DBI driver for CSV files
author: 
  - Jochen Wiedmann
  - Jeff Zucker
  - H.Merijn Brand <h.m.brand@xs4all.nl>
  - Jens Rehsack <rehsack@cpan.org>
build_requires: 
  Config: 0
  Cwd: 0
  Encode: 0
  Test::Harness: 0
  Test::More: '0.90'
  charnames: 0
configure_requires: 
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: Author
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBD-CSV
provides: 
  DBD::CSV: 
    file: lib/DBD/CSV.pm
    version: '0.37'
recommends: 
  Test::More: '0.98'
  perl: '5.016002'
requires: 
  DBD::File: '0.41'
  DBI: '1.623'
  SQL::Statement: '1.402'
  Text::CSV_XS: '0.94'
  perl: '5.008001'
resources: 
  license: http://dev.perl.org/licenses/
  repository: http://repo.or.cz/r/DBD-CSV.git
version: '0.37'
x_installdirs: site
