--- #YAML:1.0
name:                    DBD::CSV
version:                 0.30
abstract:                DBI driver for CSV files
license:                 perl
author:              
    - Jochen Wiedmann
    - Jeff Zucker
    - H.Merijn Brand <h.m.brand@xs4all.nl>
    - Jens Rehsack
generated_by:            Author
distribution_type:       module
provides:
    DBD::CSV:
        file:            lib/DBD/CSV.pm
        version:         0.30
requires:     
    perl:                5.008001
    DBI:                 1.611
    DBD::File:           0.38
    SQL::Statement:      1.25
    Text::CSV_XS:        0.71
configure_requires:
    ExtUtils::MakeMaker: 0
build_requires:
    perl:                5.008001
    Config:              0
    Test::Harness:       0
    Test::More:          0
    Encode:              0
    Cwd:                 0
    charnames:           0
recommends:     
    perl:                5.012001
    Text::CSV_XS:        0.73
    SQL::Statement:      1.27
installdirs:             site
resources:
    license:             http://dev.perl.org/licenses/
    repository:          http://repo.or.cz/r/DBD-CSV.git
meta-spec:
    version:             1.4
    url:                 http://module-build.sourceforge.net/META-spec-v1.4.html
