--- #YAML:1.1
name:                    DBD::CSV
version:                 0.27
abstract:                DBI driver for CSV files
license:                 perl
author:              
    - Jochen Wiedmann
    - Jeff Zucker
    - H.Merijn Brand <h.m.brand@xs4all.nl>
generated_by:            Author
distribution_type:       module
provides:
    DBD::CSV:
        file:            lib/DBD/CSV.pm
        version:         0.27
requires:     
    perl:                5.005003
    DBI:                 1.00
    DBD::File:           0.37
    SQL::Statement:      1.23
    Text::CSV_XS:        0.64
configure_requires:
    ExtUtils::MakeMaker: 0
build_requires:
    perl:                5.005003
    Config:              0
    Test::Harness:       0
    Test::More:          0
recommends:     
    perl:                5.010001
    Text::CSV_XS:        0.71
    DBI:                 1.611
    DBD::File:           0.38
installdirs:             site
resources:
    license:             http://dev.perl.org/licenses/
    repository:          http://repo.or.cz/w/DBD-CSV.git
meta-spec:
    version:             1.4
    url:                 http://module-build.sourceforge.net/META-spec-v1.4.html
