--- 
abstract: DBI driver for CSV files
author: 
  - Jochen Wiedmann
  - Jeff Zucker
  - H.Merijn Brand <h.m.brand@xs4all.nl>
  - Jens Rehsack <rehsack@cpan.org>
build_requires: 
  Config: 0
configure_requires: 
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: Author, CPAN::Meta::Converter version 2.131560
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBD-CSV
provides: 
  DBD::CSV: 
    file: lib/DBD/CSV.pm
    version: '0.40'
recommends: 
  Test::More: '0.98'
  perl: '5.016003'
requires: 
  Cwd: 0
  DBD::File: '0.42'
  DBI: '1.628'
  Encode: 0
  SQL::Statement: '1.405'
  Test::Harness: 0
  Test::More: '0.90'
  Text::CSV_XS: '1.01'
  charnames: 0
  perl: '5.008001'
resources: 
  license: http://dev.perl.org/licenses/
  repository: https://github.com/perl5-dbi/DBD-CSV.git
version: '0.40'
x_installdirs: site
